---

- name: "Add filesystem options for /tmp"
  when: not rhel9cis_tmp_svc
  vars:
    mount_point: '/tmp'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "{{ prelim_mount_point_fs_and_options[mount_point]['src'] }}"
    state: present
    fstype: "{{ prelim_mount_point_fs_and_options[mount_point]['fs_type'] }}"
    opts: "{{ prelim_mount_point_fs_and_options[mount_point]['options'] | unique | join(',') }}"
  listen: "Remount /tmp"

- name: "Remounting /tmp"
  when: not rhel9cis_tmp_svc
  vars:
    mount_point: '/tmp'
  ansible.posix.mount:
    path: "{{ mount_point }}"
    state: remounted
  failed_when: false
  register: discovered_remount_tmp
  listen: "Remount /tmp"

- name: "Reloading /tmp systemd service"
  when: rhel9cis_tmp_svc
  ansible.builtin.systemd:
    name: tmp.mount
    state: reloaded
    daemon_reload: true
  failed_when: false
  register: discovered_remount_tmp_systemd
  listen: "Remount /tmp"

- name: "/tmp mount busy, reboot required to apply changes | Warning"
  when: (discovered_remount_tmp is defined and discovered_remount_tmp.failed | default(false)) or
        (discovered_remount_tmp_systemd is defined and discovered_remount_tmp_systemd.failed | default(false))
  ansible.builtin.debug:
    msg: "Warning: /tmp mount busy, reboot required to apply changes"
  listen: "Remount /tmp"

- name: "/tmp mount busy, reboot required to apply changes | Set facts"
  when: (discovered_remount_tmp is defined and discovered_remount_tmp.failed | default(false)) or
        (discovered_remount_tmp_systemd is defined and discovered_remount_tmp_systemd.failed | default(false))
  vars:
    warn_control_id: "/tmp mount busy, reboot required"
  ansible.builtin.set_fact:
    change_requires_reboot: true
    warn_control_list: "{{ warn_control_list }} [{{ warn_control_id }}]"
    warn_count: "{{ warn_count | int + 1 }}"
  listen: "Remount /tmp"
