---

- name: "3.4.1.1 | L1 | PATCH | Ensure a Firewall package is installed"
  package:
      name: "{{ rhel9cis_firewall }}"
      state: present
  when:
      - rhel9cis_rule_3_4_1_1
      - not system_is_container
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.1.1
