---

- name: "2.4 | AUDIT | Ensure nonessential services are removed or masked"
  block:
      - name: "2.4 | AUDIT | Ensure nonessential services are removed or masked | Get list of services"
        shell: systemctl list-units --type=service
        changed_when: false
        failed_when: false
        check_mode: no
        register: rhel9cis_2_4_services

      - name: "2.4 | AUDIT | Ensure nonessential services are removed or masked | Display list of services"
        debug:
            msg:
                - "Warning! Below are the list of services, both active and inactive"
                - "Please review to make sure all are essential"
                - "{{ rhel9cis_2_4_services.stdout_lines }}"
  when:
      - rhel9cis_rule_2_4
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - services
      - rule_2.4
