---

- name: "1.1.2.6.1 | AUDIT | Ensure separate partition exists for /var/log"
  when:
    - required_mount not in mount_names
    - rhel9cis_rule_1_1_2_6_1
  tags:
    - level2-server
    - level2-workstation
    - audit
    - mounts
    - rule_1_1_2.6.1
    - NIST800-53R5_CM-7
  vars:
    warn_control_id: '1.1.2.6.1'
    required_mount: '/var/log'
  block:
    - name: "1.1.2.6.1 | AUDIT | Ensure separate partition exists for /var/log | Absent"
      ansible.builtin.debug:
        msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

    - name: "1.1.2.6.1 | AUDIT | Ensure separate partition exists for /var/log | Present"
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: |
    "1.1.2.6.2 | PATCH | Ensure nodev option set on /var/log partition
     1.1.2.6.3 | PATCH | Ensure nosuid option set on /var/log partition
     1.1.2.6.4 | PATCH | Ensure noexec option set on /var/log partition"
  when:
    - item.mount == "/var/log"
    - rhel9cis_rule_1_1_2_6_2 or
      rhel9cis_rule_1_1_2_6_3 or
      rhel9cis_rule_1_1_2_6_4
  tags:
    - level1-server
    - level1-workstation
    - patch
    - mounts
    - rule_1.1.2.6.2
    - rule_1.1.2.6.3
    - rule_1.1.2.6.4
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
  ansible.posix.mount:
    name: /var/log
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    state: present
    opts: "{{ item.options }}{% if ('nodev' not in item.options and rhel9cis_rule_1_1_2_6_2) %},nodev{% endif %}{% if ('nosuid' not in item.options and rhel9cis_rule_1_1_2_6_3) %},nosuid{% endif %}{% if ('noexec' not in item.options and rhel9cis_rule_1_1_2_6_4) %},noexec{% endif %}"
  loop: "{{ ansible_facts.mounts }}"
  loop_control:
    label: "{{ item.device }}"
  notify: Change_requires_reboot
