---

- name: "OPTIONAL | PATCH | Ensure saved nftables ruleset is loaded at boot"
  when:
    - rhel9cis_nft_tables_saveruleset
    - rhel9cis_rule_4_3_1 or rhel9cis_rule_4_3_2 or
      rhel9cis_rule_4_3_3 or rhel9cis_rule_4_3_4
  tags:
    - level1-server
    - level1-workstation
    - patch
    - nftables
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/nftables.conf
    line: 'include "{{ rhel9cis_nft_tables_savefile }}"'
    regexp: '^include "{{ rhel9cis_nft_tables_savefile }}"$'
    create: true
    owner: root
    group: root
    mode: 'go-rwx'

- name: "OPTIONAL | PATCH | Create Table if doesn't exist and required"
  when:
    - rhel9cis_nft_tables_autonewtable
    - rhel9cis_rule_4_3_1 or rhel9cis_rule_4_3_2 or
      rhel9cis_rule_4_3_3 or rhel9cis_rule_4_3_4
  tags:
    - level1-server
    - level1-workstation
    - patch
    - nftables
    - rule_4.3.1
    - rule_4.3.2
    - rule_4.3.3
    - rule_4.3.4
  ansible.builtin.command: "nft add table inet {{ rhel9cis_nft_tables_tablename }}"
  changed_when: false

- name: "4.3.1 | PATCH | Ensure nftables base chains exist"
  when: rhel9cis_rule_4_3_1
  tags:
    - level1-server
    - level1-workstation
    - patch
    - nftables
    - rule_4.3.1
    - NIST800-55_CA-9
  block:
    - name: "4.3.1 | AUDIT | Ensure nftables base chains exist | Get current chains for INPUT"
      ansible.builtin.shell: |
        set -o pipefail
        nft list ruleset | grep 'hook input'
      args:
        executable: "{{ rhel9cis_shell_executable }}"
      changed_when: false
      failed_when: false
      register: discovered_nftables_input_chains

    - name: "4.3.1 | AUDIT | Ensure nftables base chains exist | Get current chains for FORWARD"
      ansible.builtin.shell: |
        set -o pipefail
        nft list ruleset | grep 'hook forward'
      args:
        executable: "{{ rhel9cis_shell_executable }}"
      changed_when: false
      failed_when: false
      register: discovered_nftables_forward_chains

    - name: "4.3.1 | AUDIT | Ensure nftables base chains exist | Get current chains for OUTPUT"
      ansible.builtin.shell: |
        set -o pipefail
        nft list ruleset | grep 'hook output'
      args:
        executable: "{{ rhel9cis_shell_executable }}"
      changed_when: false
      failed_when: false
      register: discovered_nftables_output_chains

    - name: "4.3.1 | AUDIT | Ensure nftables base chains exist | Display chains for review"
      when: not rhel9cis_nft_tables_autochaincreate
      ansible.builtin.debug:
        msg:
          - "Below are the current INPUT chains"
          - "{{ discovered_nftables_input_chains.stdout_lines }}"
          - "Below are the current FORWARD chains"
          - "{{ discovered_nftables_forward_chains.stdout_lines }}"
          - "Below are teh current OUTPUT chains"
          - "{{ discovered_nftables_output_chains.stdout_lines }}"

    - name: "4.3.1 | PATCH | Ensure nftables base chains exist | Create chains if needed"
      when:
        - rhel9cis_nft_tables_autochaincreate
        - item.check.stdout | default('') | length == 0
      ansible.builtin.command: >-
        nft create chain inet "{{ rhel9cis_nft_tables_tablename }}"
        {{ item.hook }} { type filter hook {{ item.hook }} priority 0 \; }
      changed_when: true
      loop:
        - { hook: input, check: "{{ discovered_nftables_input_chains }}" }
        - { hook: forward, check: "{{ discovered_nftables_forward_chains }}" }
        - { hook: output, check: "{{ discovered_nftables_output_chains }}" }

- name: "4.3.2 | PATCH | Ensure nftables established connections are configured"
  when: rhel9cis_rule_4_3_2
  tags:
    - level1-server
    - level1-workstation
    - patch
    - nftables
    - rule_4.3.2
    - NIST800-55_CA-9
  block:
    - name: "4.3.2 | AUDIT | Ensure nftables established connections are configured | Gather incoming connection rules"
      ansible.builtin.shell: |
        set -o pipefail
        nft list ruleset | awk '/hook input/,/}/' | grep -E 'ip protocol (tcp|udp|icmp) ct state'
      args:
        executable: "{{ rhel9cis_shell_executable }}"
      changed_when: false
      failed_when: false
      register: discovered_nftables_inconnectionrule

    - name: "4.3.2 | AUDIT | Ensure nftables established connections are configured | Gather outbound connection rules"
      ansible.builtin.shell: |
        set -o pipefail
        nft list ruleset | awk '/hook output/,/}/' | grep -E 'ip protocol (tcp|udp|icmp) ct state'
      args:
        executable: "{{ rhel9cis_shell_executable }}"
      changed_when: false
      failed_when: false
      register: discovered_nftables_outconnectionrule

    - name: "4.3.2 | PATCH | Ensure nftables established connections are configured | Add input tcp established accept policy"
      when: '"ip protocol tcp ct state established accept" not in discovered_nftables_inconnectionrule.stdout'
      ansible.builtin.command: nft add rule inet "{{ rhel9cis_nft_tables_tablename }}" input ip protocol tcp ct state established accept
      changed_when: true

    - name: "4.3.2 | PATCH | Ensure nftables established connections are configured | Add input udp established accept policy"
      when: '"ip protocol udp ct state established accept" not in discovered_nftables_inconnectionrule.stdout'
      ansible.builtin.command: nft add rule inet "{{ rhel9cis_nft_tables_tablename }}" input ip protocol udp ct state established accept
      changed_when: true

    - name: "4.3.2 | PATCH | Ensure nftables established connections are configured | Add input icmp established accept policy"
      when: '"ip protocol icmp ct state established accept" not in discovered_nftables_inconnectionrule.stdout'
      ansible.builtin.command: nft add rule inet "{{ rhel9cis_nft_tables_tablename }}" input ip protocol icmp ct state established accept
      changed_when: true

    - name: "4.3.2 | PATCH | Ensure nftables established connections are configured | Add output tcp new, related, established accept policy"
      when: '"ip protocol tcp ct state established,related,new accept" not in discovered_nftables_outconnectionrule.stdout'
      ansible.builtin.command: nft add rule inet "{{ rhel9cis_nft_tables_tablename }}" output ip protocol tcp ct state new,related,established accept
      changed_when: true

    - name: "4.3.2 | PATCH | Ensure nftables established connections are configured | Add output udp new, related, established accept policy"
      when: '"ip protocol udp ct state established,related,new accept" not in discovered_nftables_outconnectionrule.stdout'
      ansible.builtin.command: nft add rule inet "{{ rhel9cis_nft_tables_tablename }}" output ip protocol udp ct state new,related,established accept
      changed_when: true

    - name: "4.3.2 | PATCH | Ensure nftables established connections are configured | Add output icmp new, related, established accept policy"
      when: '"ip protocol icmp ct state established,related,new accept" not in discovered_nftables_outconnectionrule.stdout'
      ansible.builtin.command: nft add rule inet "{{ rhel9cis_nft_tables_tablename }}" output ip protocol icmp ct state new,related,established accept
      changed_when: true

- name: "4.3.3 | PATCH | Ensure nftables default deny firewall policy"
  when: rhel9cis_rule_4_3_3
  tags:
    - level1-server
    - level1-workstation
    - patch
    - nftables
    - rule_4.3.3
    - NIST800-55_CA-9
  block:
    - name: "4.3.3 | AUDIT | Ensure nftables default deny firewall policy | Check for hook input deny policy"
      ansible.builtin.shell: |
        set -o pipefail
        nft list table inet "{{ rhel9cis_nft_tables_tablename }}" | grep 'hook input'
      args:
        executable: "{{ rhel9cis_shell_executable }}"
      failed_when: false
      changed_when: false
      register: discovered_nftables_inputpolicy

    - name: "4.3.3 | AUDIT | Ensure nftables default deny firewall policy | Check for hook forward deny policy"
      ansible.builtin.shell: |
        set -o pipefail
        nft list table inet "{{ rhel9cis_nft_tables_tablename }}" | grep 'hook forward'
      args:
        executable: "{{ rhel9cis_shell_executable }}"
      failed_when: false
      changed_when: false
      register: discovered_nftables_forwardpolicy

    - name: "4.3.3 | AUDIT | Ensure nftables default deny firewall policy | Check for hook output deny policy"
      ansible.builtin.shell: |
        set -o pipefail
        nft list table inet "{{ rhel9cis_nft_tables_tablename }}" | grep 'hook output'
      args:
        executable: "{{ rhel9cis_shell_executable }}"
      failed_when: false
      changed_when: false
      register: discovered_nftables_outputpolicy

    - name: "4.3.3 | AUDIT | Ensure nftables default deny firewall policy | Check for SSH allow"
      ansible.builtin.shell: |
        set -o pipefail
        nft list table inet "{{ rhel9cis_nft_tables_tablename }}" | grep -E 'dport (22|ssh)'
      args:
        executable: "{{ rhel9cis_shell_executable }}"
      failed_when: false
      changed_when: false
      register: discovered_nftables_sshallowcheck

    - name: "4.3.3 | PATCH | Ensure nftables default deny firewall policy | Enable SSH traffic"
      when: not discovered_nftables_sshallowcheck.stdout is search('tcp dport (22|ssh) accept')
      ansible.builtin.command: nft add rule inet "{{ rhel9cis_nft_tables_tablename }}" input tcp dport ssh accept
      changed_when: true

    - name: "4.3.3 | PATCH | Ensure nftables default deny firewall policy | Set hook input deny policy"
      when: not discovered_nftables_inputpolicy.stdout is search('hook input priority (0|filter); policy drop;')
      ansible.builtin.command: nft chain inet "{{ rhel9cis_nft_tables_tablename }}" input { policy drop \; }
      changed_when: true

    - name: "4.3.3 | PATCH | Ensure nftables default deny firewall policy | Create hook forward deny policy"
      when: not discovered_nftables_forwardpolicy.stdout is search('hook forward priority (0|filter); policy drop;')
      ansible.builtin.command: nft chain inet "{{ rhel9cis_nft_tables_tablename }}" forward { policy drop \; }
      changed_when: true

    - name: "4.3.3 | PATCH | Ensure nftables default deny firewall policy | Create hook output deny policy"
      when: not discovered_nftables_outputpolicy.stdout is search('hook output priority (0|filter); policy drop;')
      ansible.builtin.command: nft chain inet "{{ rhel9cis_nft_tables_tablename }}" output { policy drop \; }
      changed_when: true

- name: "4.3.4 | PATCH | Ensure nftables loopback traffic is configured"
  when: rhel9cis_rule_4_3_4
  tags:
    - level1-server
    - level1-workstation
    - patch
    - nftables
    - rule_4.3.4
    - NIST800-55_CA-9
  block:
    - name: "4.3.4 | AUDIT | Ensure nftables loopback traffic is configured | Gather iif lo accept existence | nftables"
      ansible.builtin.shell: |
        set -o pipefail
        nft list ruleset | awk '/hook input/,/}/' | grep 'iif "lo" accept'
      args:
        executable: "{{ rhel9cis_shell_executable }}"
      changed_when: false
      failed_when: false
      register: discovered_nftables_iiflo

    - name: "4.3.4 | AUDIT | Ensure nftables loopback traffic is configured | Gather ip saddr existence | nftables"
      ansible.builtin.shell: |
        set -o pipefail
        nft list ruleset | awk '/hook input/,/}/' | grep 'ip saddr'
      args:
        executable: "{{ rhel9cis_shell_executable }}"
      changed_when: false
      failed_when: false
      register: discovered_nftables_ipsaddr

    - name: "4.3.4 | AUDIT | Ensure nftables loopback traffic is configured | Gather ip6 saddr existence | nftables"
      ansible.builtin.shell: |
        set -o pipefail
        nft list ruleset | awk '/hook input/,/}/' | grep 'ip6 saddr'
      args:
        executable: "{{ rhel9cis_shell_executable }}"
      changed_when: false
      failed_when: false
      register: discovered_nftables_ip6saddr

    - name: "4.3.4 | PATCH | Ensure nftables loopback traffic is configured | Set iif lo accept rule | nftables"
      when: '"iif \"lo\" accept" not in discovered_nftables_iiflo.stdout'
      ansible.builtin.command: nft add rule inet "{{ rhel9cis_nft_tables_tablename }}" input iif lo accept
      changed_when: true

    - name: "4.3.4 | PATCH | Ensure nftables loopback traffic is configured | Set ip saddr rule | nftables"
      when: '"ip saddr 127.0.0.0/8 counter packets 0 bytes 0 drop" not in discovered_nftables_ipsaddr.stdout'
      ansible.builtin.command: nft add rule inet "{{ rhel9cis_nft_tables_tablename }}" input ip saddr 127.0.0.0/8 counter drop
      changed_when: true

    - name: "4.3.4 | PATCH | Ensure nftables loopback traffic is configured | Set ip6 saddr rule | nftables"
      when: '"ip6 saddr ::1 counter packets 0 bytes 0 drop" not in discovered_nftables_ip6saddr.stdout'
      ansible.builtin.command: nft add rule inet "{{ rhel9cis_nft_tables_tablename }}" input ip6 saddr ::1 counter drop
      changed_when: true

- name: "OPTIONAL | PATCH | Persist the nftables ruleset"
  when:
    - rhel9cis_nft_tables_saveruleset
    - rhel9cis_rule_4_3_1 or rhel9cis_rule_4_3_2 or
      rhel9cis_rule_4_3_3 or rhel9cis_rule_4_3_4
  tags:
    - level1-server
    - level1-workstation
    - patch
    - nftables
  block:
    - name: "OPTIONAL | AUDIT | Persist the nftables ruleset | Capture live ruleset"
      ansible.builtin.command: nft list ruleset
      changed_when: false
      check_mode: false
      register: discovered_nftables_live_ruleset

    - name: "OPTIONAL | PATCH | Persist the nftables ruleset | Write ruleset file"
      ansible.builtin.copy:
        content: |
          flush ruleset
          {{ discovered_nftables_live_ruleset.stdout }}
        dest: "{{ rhel9cis_nft_tables_savefile }}"
        owner: root
        group: root
        mode: 'go-rwx'
